version: "3.9"

volumes:
  dynamodb:
  s3:

services:
  dynamodb:
    image: "amazon/dynamodb-local"
    user: "root"
    command: "-jar DynamoDBLocal.jar -dbPath /data"
    ports:
      - "8000:8000"
    volumes:
      - "dynamodb:/data"

  dynamodb-admin:
    image: "aaronshaf/dynamodb-admin"
    ports:
      - "8001:8001"
    environment:
      - "DYNAMO_ENDPOINT=http://dynamodb:8000"
      - "AWS_ACCESS_KEY_ID=local"
      - "AWS_SECRET_ACCESS_KEY=verysecret"
      - "AWS_REGION=eu-west-1"

  s3:
    image: "minio/minio"
    command: "server /data"
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ROOT_USER=local"
      - "MINIO_ROOT_PASSWORD=verysecret"
      - "MINIO_REGION_NAME=eu-west-1"
    volumes:
      - "s3:/data"
