name: check

on: [push]

jobs:
  e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn

      - name: Start background services
        run: docker-compose up -d
      - name: Start application
        run: yarn build && PORT=3000 yarn start &

      - name: Run tests
        run: yarn test:e2e

  check:
    name: Run basic checks and unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn

      - name: Check formatting and types
        run: yarn run check

      - name: Run tests
        run: yarn run test
      - name: Build next app
        run: yarn run build
