name: check

on: [push]

jobs:
  check:
    name: Run checks and tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install dependencies
        run: make init

      - name: Start background services
        run: make dev-services

      - name: Run all checks and tests
        run: >
          xvfb-run --server-args="-screen 0 1280x720x24"
          make -j check test TESTCAFE_BROWSERS=all TESTCAFE_APP_INIT_DELAY=30000

      - name: Build next app
        run: yarn run build
