name: check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn

      - name: Check formatting
        run: yarn run check

      - name: Run tests
        run: yarn run test
      - name: Build next app
        run: yarn run build
