name: End-to-End Test

on: [push]

jobs:
  test:
    name: Run TestCafe tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome e2e/"
