name: frontend
on: [push]
jobs:
  check-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15"
      - name: Install packages
        run: make init-frontend
      - name: Run checks
        run: make check-frontend
