name: infra
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15"
      - name: Install packages
        run: make init-infra
      - name: Run checks
        run: make check-infra
      - name: cdk synthesize
        run: |
          cd infra/
          yarn cdk synthesize Repository
          yarn cdk synthesize Infra
